import Head from 'next/head'
import Image from 'next/image'
import {Inter} from '@next/font/google'
import styles from '../styles/Home.module.css'
import Link from "next/link";

const inter = Inter({subsets: ['latin']})

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>

        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <meta name="robots" content="noindex,nofollow"/>

        <link rel="preconnect" href="https://fonts.gstatic.com"/>
        <link rel="stylesheet" type="text/css" href="https://unpkg.com/aos@2.3.1/dist/aos.css"/>
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&amp;display=swap"
              rel="stylesheet"/>
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;600&display=swap"
              rel="stylesheet"/>
        <link rel="stylesheet" type="text/css" href="../src/styles/bootstrap.css"/>
        <link rel="stylesheet" type="text/css" href="../src/styles/style.css"/>
      </Head>
      <main className={styles.main}>

        <Link href={'/blog'}>
          <button>GO TO BLOG</button>
        </Link>
      </main>
    </>
  )
}
