import Head from 'next/head'
import Link from "next/link";
import {GetServerSideProps} from "next";
import axios from "axios";
import sequelize from "@server/database/models/conn";
import User from "@server/database/models/User";
import Categories from "../components/Categories";
import ScrollReview from "../components/ScrollReview";
import {ReviewDto} from "@server/dto/ReviewDto";
import styles from "./Owl.module.css"

const dreview: ReviewDto = {
  fName: "Aissata",
  lName: "Kane",
  entity: "F.A Squad",
  rating: 4,
  content: "ipsum dolor sit amet consectetur adipisicing elit. Quam recusandae dignissimos possimus aliquam, officiis neque tenetur quibusdam nisi culpa accusamus quae voluptates commodi libero, dolore distinctio est repellat a voluptatem."
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <main>
        <div className={"row d-flex gap-2"}>
          <Link href={'merchant-review'}>
            MERCHANT REVIEW
          </Link>
          <Link href={'product-review'}>
            PRODUCT REVIEW
          </Link>
        </div>

        <section className="py-5 home__hero">
          <div className="container">
            <div className="row d-flex align-items-center">
              <div className="col-lg-6 py-5">
                <h1 className="display-2"><span className="text-primary">Trusted Reviews</span> on
                  the <span>Blockchain</span></h1>
                <p className="lead">VeritaTrust is a decentralized &amp; transparent customer feedback on the
                  Blockchain.</p>
                <p className="lead text-green">Share your genuine experience and get rewards.</p>
                <Link className="btn btn-success btn-lg me-4 text-white px-5" href="/Explore">Explore</Link>
                <Link className="btn btn-outline-primary btn-lg px-5" href="/Create">Create</Link>
              </div>
              <div className="col-lg-6 py-5">
                <img src={'/img/reviews-homepage.jpg'} alt="reviews"/>
              </div>
            </div>
          </div>
        </section>
        <Categories/>
        <div className="col-lg-6 mx-auto">
          <p className="lead text-center">Looking for a specific review ?<br/>Look for reviews about the product you
            want.</p>
          <a className="btn btn-primary w-100" href="#">See all reviews</a>
        </div>
        <section className="home__logos bg-success py-3">
          <div className="container">
            <div className="row">
              <div className="col-6 col-lg-2 text-center mb-3">
                <img className="" src={'/img/lorem-portrait.jpg'} alt="" height="60" width="60"/>
              </div>
              <div className="col-6 col-lg-2 text-center mb-3">
                <img className="" src={'/img/lorem-portrait.jpg'} alt="" height="60" width="60"/>
              </div>
              <div className="col-6 col-lg-2 text-center mb-3">
                <img className="" src={'/img/lorem-portrait.jpg'} alt="" height="60" width="60"/>
              </div>
              <div className="col-6 col-lg-2 text-center mb-3">
                <img className="" src={'/img/lorem-portrait.jpg'} alt="" height="60" width="60"/>
              </div>
              <div className="col-6 col-lg-2 text-center mb-3">
                <img className="" src={'/img/lorem-portrait.jpg'} alt="" height="60" width="60"/>
              </div>
              <div className="col-6 col-lg-2 text-center mb-3">
                <img className="" src={'/img/lorem-portrait.jpg'} alt="" height="60" width="60"/>
              </div>
            </div>
          </div>
        </section>
        <section className="home__reviews py-5">
          <div className="container">
            <div className="row mb-4">
              <h4 className="display-6 text-success">Recent Reviews</h4>
            </div>
          </div>
          <div className="">
            <div className="mb-4">
              <div className={styles.owlCarousel}>
                <div className="item">
                  <ScrollReview review={dreview}/>
                  <ScrollReview review={dreview}/>
                </div>
                <div className="item">
                  <ScrollReview review={dreview}/>
                  <ScrollReview review={dreview}/>
                </div>
                <div className="item">
                  <ScrollReview review={dreview}/>
                  <ScrollReview review={dreview}/>
                </div>
                <div className="item">
                  <ScrollReview review={dreview}/>
                  <ScrollReview review={dreview}/>
                </div>

              </div>


            </div>
          </div>
        </section>
      </main>
    </>
  )
}


export const getServerSideProps: GetServerSideProps = async () => {
  try {
    console.log('!!!!AHASHDHSA')


    const {data} = await axios.get(
      `http://localhost:3000/api`,
    );
    console.log('NAME', data);

    const userRepo = sequelize.getRepository(User)
    const a = await userRepo.findAll<User>()
    console.log('!AAA from getServerSideProps!', a)

    return {props: {name: "BURAK"}};
  } catch (error) {
    console.log(error)
    return {props: {name: "BURAK"}};
  }
}
