import {GetServerSideProps, NextPage} from "next";
import axios from "axios";
import Head from "next/head";
import {useTranslation} from "next-i18next";

interface Props {
  merchantReviews: MerchantReview[]
}

type MerchantReview = {
  id: string;
  userId: string;
  status: string;
  title: string;
  content: string;
  rating: string;
  experienceDate: string;
}

const MerchantReview: NextPage<Props> = ({merchantReviews}) => {

  const { t: translate } = useTranslation('about')
  console.log(translate('about_us_text'))

  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app"/>
        <title>Veritatrust - Merchant Review</title>
      </Head>
      <main>
        <div className="row d-flex align-items-center">
          <form className="row d-flex align-items-center" id="review_form" method="POST" action="/api/merchant-review-form">
            <div className="container">

              <div className="row d-flex align-items-center">
                <div className="col-11 col-lg-8 pt-3 mx-auto text-center">
                  <h3>Partagez votre avis sur <span>Xxxxx</span></h3>
                  <p>Vos témoignages aident les autres clients à prendre les bonnes décisions.</p>
                </div>
                <div className="col-11 col-lg-8 py-3 mx-auto">
                  <ul className="nav nav-pills nav-fill">
                    <li className="nav-item">
                      <a className="nav-link active" aria-current="page" href="./merchant_review_form"><span
                        className="badge text-bg-success text-white rounded-circle">1</span> Votre avis sur
                        l&apos;entreprise</a>
                    </li>
                    <li className="nav-item">
                      <a className="nav-link" href="./product_review_form"><span
                        className="badge text-bg-success text-white rounded-circle">2</span> Votre avis sur les produits</a>
                    </li>
                  </ul>
                </div>

                <div className="col-11 col-lg-8 py-4 px-lg-4 mx-auto bg-light rounded-5">
                  <div className="form__header">
                    <div className="row d-flex align-items-center">
                      <div
                        className="col-8 col-md-4 col-xl-3 d-flex rounded-4 border bg-white visuel-mark logo mx-auto">
                        <img className="align-self-center m-0"
                             src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Shoei_Logo.svg/2560px-Shoei_Logo.svg.png"
                             alt="Merchant name"/>
                      </div>
                      <div className="col-12 col-md-8 col-xl-9">
                        <div className="form__header__note">
                          <p className="lead">Donnez votre note</p>
                          <div className="form__star mb-3 d-flex justify-content-start">
                            <input className="star star__1" id="star-1" type="radio" name="star" value="1"/>
                            <label className="star star__1" htmlFor="star-1"></label>
                            <input className="star star__2" id="star-2" type="radio" name="star" value="2"/>
                            <label className="star star__2" htmlFor="star-2"></label>
                            <input className="star star__3" id="star-3" type="radio" name="star" value="3"/>
                            <label className="star star__3" htmlFor="star-3"></label>
                            <input className="star star__4" id="star-4" type="radio" name="star" value="4"/>
                            <label className="star star__4" htmlFor="star-4"></label>
                            <input className="star star__5" id="star-5" type="radio" name="star" value="5"/>
                            <label className="star star__5" htmlFor="star-5"></label>

                          </div>
                          <p><strong>5 étoiles :</strong> excellent !</p>
                        </div>
                      </div>
                    </div>
                  </div>
                  <hr/>
                  <div className="form__content">
                    <p className="lead mt-3 mb-0">Rédigez un titre</p>
                    <input className="form-control" type="text" name="titre" id="titre" required/>
                    <p className="lead mb-0">Rédigez votre avis</p>
                    <textarea className="form-control" name="content" id="content"
                              placeholder="Écrivez votre avis ici. Parlez de votre expérience sans utiliser de langage offensant. Laissez un témoignage honnête, utile et constructif."
                              required></textarea>
                    <p className="lead mt-3 mb-0">Indiquez la date d&apos;expérience</p>
                    <input className="form-control" type="date" max="2022-06-28" name="date" id="date" required/>
                  </div>
                  <div className="form__footer">
                    <div className="h-captcha" data-sitekey="3b23a8ba-8c70-490f-b499-63b74fd9e7be"></div>
                    <div id="captcha"></div>

                    <span id="error"></span>

                    <div className="d-grid gap-2">
                      <button type="submit" className="btn-block btn btn-primary btn-lg text-uppercase text-right"
                              id="btn">Publier
                      </button>
                    </div>

                  </div>
                </div>


              </div>

            </div>
          </form>

        </div>
      </main>
    </>
  )
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  console.log('ENVENEN', process.env.ENV)
  try {
    const {data} = await axios.get(
      `http://localhost:3000/api/hello`,
    );
    console.log('NAME', data);
    const merchantReviews = [] as MerchantReview[];
    return {props: {merchantReviews}};
  } catch (error) {
    return {
      redirect: {
        permanent: false,
        destination: process.env.NEXT_PUBLIC_HOMEPAGE_URL,
      },
      props: {},
    };
  }
}

export default MerchantReview;
