import {NextPage} from "next";
import Head from "next/head";
import {useTranslation} from "next-i18next";
import {useRouter} from "next/router";
import {serverSideTranslations} from "next-i18next/serverSideTranslations";
import Link from "next/link";

const ValidReview: NextPage = () => {
  const {t: translateCommon} = useTranslation('common')
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app"/>
        <title>Veritatrust Product Valid Review Page</title>
      </Head>
      <main>
        <section className="py-5 form">
          <div className="container">
            <div className="row d-flex align-items-center">
              <div className="col-11 col-lg-8 pt-3 mx-auto text-center">
                <p>
                  {translateCommon('product_form_testimonal_msg')}
                </p>
              </div>
              <div className="col-11 col-lg-8 py-3 mx-auto position-relative">
                <ul className="step-reviews nav text-center">
                  <li className="nav-item w-33 step-1 done">
                    <span className="badge rounded-circle">1</span>
                    <p className="mb-0">
                      {translateCommon('merchant_form_message_opinion')}
                    </p>
                  </li>
                  <li className="nav-item w-33 step-2 done">
                    <span className="badge rounded-circle">2</span>
                    <p className="mb-0">
                      {translateCommon('merchant_form_message_opinion2')}
                    </p>
                  </li>
                  <li className="nav-item w-33 step-3 active">
                    <span className="badge rounded-circle">3</span>
                    <p className="mb-0" aria-current="page">
                      {translateCommon('validated_message')}
                    </p>
                  </li>
                </ul>
                <div id="line">
                  <div id="line-progress"></div>
                </div>
              </div>
              <div className="col-11 col-lg-8 py-4 px-lg-4 mx-auto result-ok">
                <div className="form__header">
                  <div className="row d-flex align-items-center justify-content-center">
                    <div className="col-12 col-md-8 col-xl-9 text-center">
                      <img className="align-self-center mb-4" src="http://dev.veritatrust.com/assets/img/coin.png"
                           alt="Product name"/>
                      <p className="lead text-green">Congratulations!<br/>Your review is validated</p>
                      <p className="">You just got rewarded with <strong>1 token &#129297;</strong> for your review.
                        Get more reward and review more.</p>
                      <p className="lead text-green">Get more reward and review more.</p>
                      <Link className="btn btn-primary"
                         href="http://dev.veritatrust.com/review?site=<%=company_name%>"> Review your Products
                        recently buy</Link>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

      </main>
    </>
  )
}

export async function getStaticProps({locale}: {
  locale: string
}) {
  return {
    props: {
      ...(await serverSideTranslations(locale, [
        'common'
      ])),
    },
  }
}

export default ValidReview;
